Mysite/api/urls.py
from django.urls import path
from .view import answers, tickets, comments_answer, comments_ticket, data, invitation

urlpatterns = [
    path('', data, name='api_data'),
    path('tickets', tickets, name='api_tickets'),
    path('answers', answers, name='api_answers'),
    path('comments_answer', comments_answer, name='api_comments_1'),
    path('comments_ticket', comments_ticket, name='api_comments_2'),
    path('invitation', invitation, name='invitation')
]

Mysite/main/urls.py
from django.urls import path
from main.views import Tickets, View
from mysite import settings

urlpatterns = [
    path('', View.main_page),
    path('dashboard', View.dashboard),
    path('profile', View.profile),
    path('tickets', Tickets.get_tickets),
    path('send_ticket', Tickets.set_ticket),
    path('rewrite/<id>', Tickets.rewrite, name='rewrite'),
    path('view_answer/<id>', Tickets.view_answers, name='view_answers'),
    path('register', View.register, name='register'),
    path('register_agent' + str(settings.REGISTER_AGENT_URL), View.register_agent, name='register_agent'),
    path('logout_user', View.logout_user),
    path('log_in', View.log_in),
    path('list_tickets', Tickets.list_tickets),
    path('answer/<id>', Tickets.answer, name='answer'),
    path('knowledge_base', Tickets.knowledge_base)
]

Mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/v1/', include('api.urls')) 
]

Mysite/main/models.py
import os
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.html import strip_tags

class TicketModel(models.Model):
    PRIORITIES = (
        ('4', 'Low'),
        ('3', 'Medium'),
        ('2', 'High'),
        ('1', 'Urgent')
    )
    TYPES = (
        ('Q', 'Question'),
        ('P', 'Problem'),
        ('I', 'Incident'),
        ('R', 'Request'),
        ('O', 'Order')
    )
    STATUSES = (
        ('N', 'New'),
        ('O', 'Open'),
        ('C', 'Closed')
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(default='Title')
    text = RichTextField(config_name='ticket_ckeditor')
    ticket_comments = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    priority = models.CharField(max_length=1, choices=PRIORITIES, default='3')
    type = models.CharField(max_length=1, choices=TYPES, default='Q')
    status = models.CharField(max_length=1, choices=STATUSES, default='N')
    num_answers = models.IntegerField(default=0)
    file = models.FileField(null=True)

    def filename(self):
        return os.path.basename(self.file.name)

    def is_from_email(self):
        return self.author.username.isdigit()

    def clear_text(self):
        return strip_tags(self.text)

    def author_username(self):
        if self.is_from_email():
            return self.author.email
        else:
            return self.author.username

    def delete(self, using=None, keep_parents=False):
        storage = self.file.storage
        if len(self.file.name) > 0:
            if storage.exists(self.file.name):
                storage.delete(self.file.name)
        if self.is_from_email():
            self.author.delete()
        super().delete()

    def short_title(self):
        if len(self.title) <= 9:
            return self.title
        else:
            dots = '...'
            return self.title[0:7] + dots

    class Meta:
        permissions = (
            ('create_tickets', 'can create tickets'),
            ('answer_tickets', 'can answer tickets')
        )

class AnswerModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ticket = models.ForeignKey(TicketModel, on_delete=models.CASCADE)
    title = models.TextField(default='Title')
    text = RichTextField()
    answer_comments = models.IntegerField(default=0)
    number = models.IntegerField(default=0)
    lock = models.BooleanField(default=False)

    def clear_text(self):
        return strip_tags(self.text)

    def author_username(self):
        return self.author.username

class CommentTicketModel(models.Model):
    ticket = models.ForeignKey(TicketModel, on_delete=models.CASCADE)
    author = models.TextField(default='Commentar')
    text = models.TextField(default='Text')
    number = models.IntegerField(default=0)

class CommentAnswerModel(models.Model):
    answer = models.ForeignKey(AnswerModel, on_delete=models.CASCADE)
    author = models.TextField(default='Commentar')
    text = models.TextField(default='Text')
    number = models.IntegerField(default=0)

Mysite/main/forms.py
from django import forms
from django.forms import TextInput, Textarea
from .models import AnswerModel, TicketModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Permission

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
    
    def save(self):
        user = super(UserForm, self).save(commit=True)
        user.user_permissions.add(Permission.objects.get(name='can create tickets'))
        return user

class AgentForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']

    def save(self):
        user = super(AgentForm, self).save(commit=True)
        user.user_permissions.add(Permission.objects.get(name='can answer tickets'))
        return user

class TicketModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TicketModelForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = False
        self.fields['text'].required = False
        self.fields['priority'].required = False
        self.fields['type'].required = False
    
    class Meta:
        model = TicketModel
        fields = ['title', 'text', 'priority', 'type']
        widgets = {
            'title': TextInput(
                    {'placeholder': ('Title')}
            ),
            'text': Textarea(
                    {'placeholder':('What do you want to know?')}
            )
        }

class AnswerModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnswerModelForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = False
        self.fields['text'].required = False

    class Meta:
        model = AnswerModel
        fields = ['title', 'text']
        widgets = {
            'title': TextInput(
                    {'placeholder': ('Title')}
            )
        }

Mysite/main/views.py
import django
from django.core.paginator import Paginator
from django.http import FileResponse, HttpResponseForbidden, HttpResponseNotFound
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.base import TemplateView

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import AnonymousUser, User
from django.contrib.auth.decorators import login_required, permission_required

from .forms import AnswerModelForm, TicketModelForm, UserForm, AgentForm
from .models import AnswerModel, TicketModel, CommentTicketModel, CommentAnswerModel
from .emails import check_emails, send_erasing_email, send_answering_email, send_meeting_email

# check_emails()

class View(TemplateView):
    def main_page(request):
        if isinstance(request.user, AnonymousUser):
            return render(request, 'main_page.html')
        else:
            return HttpResponseRedirect('/dashboard')
        
    
    def register_agent(request):
        kind = 1
        if isinstance(request.user, User):
            return HttpResponseRedirect('/dashboard')
        if request.method == 'POST':
            form = AgentForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return HttpResponseRedirect('/dashboard')
        else:
            form = AgentForm()
        return render(request, 'login_user.html', {'form': form, 'kind':kind})
    
    def register(request):
        kind = 2
        if isinstance(request.user, User):
            return HttpResponseRedirect('/dashboard')
        if request.method == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return HttpResponseRedirect('/dashboard')
        else:
            form = UserForm()
        return render(request, 'login_user.html', {'form': form, 'kind':kind})
    
    def logout_user(request):
        logout(request)
        return HttpResponseRedirect('/')
    
    def log_in(request):
        kind = 3
        if isinstance(request.user, User):
            return HttpResponseRedirect('/dashboard')
        if request.method == 'POST':
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid:
                username = form.data['username']
                password = form.data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect('/dashboard')
                elif User.objects.filter(username=username).exists() == False:
                    messages.error(request, 'Wrong username')
                else:
                    messages.error(request, 'Wrong password')
        form = AuthenticationForm()
        return render(request, 'login_user.html', {'form': form, 'kind':kind})
    
    @login_required(login_url='/log_in')
    def dashboard(request):
        tickets = None
        if request.user.has_perm('main.create_tickets'):
            tickets = TicketModel.objects.all().filter(author=request.user).exclude(status='C').order_by('priority')
        if request.user.has_perm('main.answer_tickets'):
            tickets = TicketModel.objects.all().exclude(status='C').order_by('priority')
        return render(request, 'dashboard.html', {'tickets':tickets})
    
    @login_required(login_url='/log_in')
    def profile(request):
        if request.method == 'POST':
            if len(request.POST.get('change-username')) > 0:
                new_username = request.POST.get('change-username')
                if User.objects.filter(username=new_username).exists() == True:
                    messages.error(request, 'This username is in use')
                else:
                    request.user.username = request.POST.get('change-username')
            
            if len(request.POST.get('change-email')) > 0:
                request.user.email = request.POST.get('change-email')
            if len(request.POST.get('change-first-name')) > 0:
                request.user.first_name = request.POST.get('change-first-name')
            if len(request.POST.get('change-last-name')) > 0:
                request.user.last_name = request.POST.get('change-last-name')
            request.user.save()
        num_tickets = TicketModel.objects.all().filter(author=request.user).count()
        return render(request, 'profile.html', {'tickets':num_tickets})

@login_required(login_url='/log_in')
class Tickets(TemplateView):
    @permission_required('main.create_tickets', raise_exception=True)
    def set_ticket(request):
        form = TicketModelForm(request.POST, request.FILES)
        if request.method == 'POST':
            if form.is_valid():
                if len(form.data.get('text')) == 0:
                    messages.error(request, 'Empty ticket!')
                elif len(form.data.get('title')) == 0:
                    messages.error(request, 'Empty title!')
                else:
                    curr = form.save(commit=False)
                    curr.author = request.user
                    if request.FILES.get('file-name') is not None:
                        if TicketModel.objects.filter(file=request.FILES.get('file-name')).exists() == True:
                            messages.error(request, 'File with that name already exists')
                            return render(request, 'send_ticket.html', {'form':form})
                        else:
                            curr.file = request.FILES.get('file-name')
                    curr.save()
                    return HttpResponseRedirect('/dashboard')
        return render(request, 'send_ticket.html', {'form':form})
    
    @permission_required('main.create_tickets', raise_exception=True)
    def get_tickets(request):
        tickets = TicketModel.objects.all().filter(author=request.user).order_by('priority')
        comments = CommentTicketModel.objects.all()
        if request.POST.get('change') is not None:
            id = int(request.POST.get('change'))
            return HttpResponseRedirect(reverse('rewrite', kwargs={'id':id}))
        if request.POST.get('answers') is not None:
            id = int(request.POST.get('answers'))
            return HttpResponseRedirect(reverse('view_answers', kwargs={'id':id}))
        if request.POST.get('comment') is not None:
            id = int(request.POST.get('comment'))
            ticket = tickets.get(id=id)
            ticket.ticket_comments += 1
            comment = CommentTicketModel.objects.create(
                                                        ticket=ticket, 
                                                        text=request.POST.get('more-info'), 
                                                        number=ticket.ticket_comments
                                                        )
            comment.save()
            ticket.save()
        if request.POST.get('file-button-name') is not None:
            id = int(request.POST.get('file-button-name'))
            ticket = tickets.get(id=id)
            filepath = str(ticket.file)
            try:
                return FileResponse(open('media/' + filepath, 'rb'))
            except Exception:
                return HttpResponseNotFound('<h1><strong>File not found</strong></h1>')
        return render(request, 'tickets.html', {'tickets':tickets, 'comments':comments})
    
    @permission_required('main.create_tickets', raise_exception=True)
    def rewrite(request, id):
        ticket = TicketModel.objects.get(pk=id)
        form = TicketModelForm(request.POST or None, instance=ticket)
        if form.is_valid():
            if len(form.data.get('text')) == 0:
                messages.error(request, 'Empty ticket!')
            elif len(form.data.get('title')) == 0:
                messages.error(request, 'Empty title!')
            else:
                form.save()
                return HttpResponseRedirect('/tickets')
        return render(request, 'send_ticket.html', {'ticket':ticket, 'form':form})
    
    @permission_required('main.create_tickets', raise_exception=True)
    def view_answers(request, id):
        ticket = TicketModel.objects.get(pk=id)
        answers = AnswerModel.objects.all().filter(ticket=ticket).order_by('number')
        comments = CommentAnswerModel.objects.all()
        if request.POST.get('comment') is not None:
            id = int(request.POST.get('comment'))
            answer = answers.get(id=id)
            if answer.lock == True:
                if answer.author != request.user:
                    return HttpResponseForbidden('<h1><strong>Forbidden action!</strong></h1>')
            answer.answer_comments += 1
            comment = CommentAnswerModel.objects.create(
                                                        answer=answer, 
                                                        author=request.user.username, 
                                                        text=request.POST.get('more'), 
                                                        number=answer.answer_comments
                                                        )
            comment.save()
            answer.save()
        return render(request, 'answer.html', {'ticket':ticket, 'answers':answers, 'comments':comments})
    
    @permission_required('main.answer_tickets', raise_exception=True)
    def list_tickets(request):
        tickets = TicketModel.objects.all().exclude(status='C').order_by('priority')
        comments = CommentTicketModel.objects.all()
        if request.POST.get('answer') is not None:
            id = int(request.POST.get('answer'))

Mysite/main/templates/dashboard.html
{% extends "layout.html" %}

{% block title %}
<title>Dashboard</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="card mt-5" style="width: 70rem;">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" id="dashboard-title">Title</th>
                    <th scope="col" id="dashboard-priority">Priority</th>
                    <th scope="col" id="dashboard-type">Type</th>
                    <th scope="col" id="dashboard-author">Author</th>
                    <th scope="col" id="dashboard-status">Status</th>
                    <th scope="col" id="dashboard-date">Date</th>
                </tr>
            </thead>
        </table>
        <div class="card-body" style="height: 400px; overflow:auto; overflow-x: hidden;">
            <table class="table table-hover mb-0 ">
                <tbody>
                    {% for ticket in tickets %}
                    <tr id="id-{{ticket.id}}" onclick="click_row(id, '{{ticket.id}}', '{{perms.main.answer_tickets}}')">
                        <th id="dashboard-title-ticket">{{ticket.short_title}}</th>
                        <td id="dashboard-priority-ticket">{{ticket.get_priority_display}}</td>
                        <td id="dashboard-type-ticket">{{ticket.get_type_display}}</td>
                        {% if ticket.is_from_email %}
                            <td id="dashboard-author-ticket"><i class="fa-solid fa-envelope ml-4"></i></td>
                        {% else %}
                            <td id="dashboard-author-ticket">{{ticket.author}}</td>
                        {% endif %}
                        <td id="dashboard-status-ticket">{{ticket.get_status_display}}</td>
                        <td id="dashboard-date-ticket">{{ticket.date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

Mysite/main/templates/knowledge_base.html
{% extends "layout.html" %}

{% block title %}
    <title>Knowledge Base</title>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% for ticket in tickets %}
<form method="post">
    {% csrf_token %}
    <div class="container d-flex justify-content-center mt-5">
        <div class="card mt-4 mb-3" style="width:55rem;" id="card-{{ticket.id}}" >
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        {% if ticket.is_from_email %}
                        <div class="m-2">
                            <i class="fa-solid fa-envelope fa-2x" style="color: cadetblue;"></i>
                        </div>
                        {% else %}
                        <p class="lead">{{ticket.author}}</p>
                        {% endif %}
                    </div>
                    <div class="col">
                        <p>{{ticket.author.email}}</p><br>
                    </div>
                    <div class="col">
                        <p>{{ticket.date}}</p><br>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">{{ticket.title}}</h5>
                <div class="border">
                    <p class="card-text m-3">{{ticket.text|safe}}</p>
                </div>
                {% if ticket.num_answers == 0 %}
                <button class="btn btn-info mt-2 btn-block" disabled>
                {% else %}
                <button class="btn btn-primary mt-2 btn-block" role="button" value="{{ticket.id}}" name="answers" id="answers-view-{{ticket.id}}">
                {% endif %}
                    Answers
                    <span class="badge badge-light">
                        {{ticket.num_answers}}
                    </span>
                </button>
                
                {% if ticket.ticket_comments == 0 %}
                <button class="btn btn-primary btn-block" disabled>
                {% else %}
                <button class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target="#collapse-{{ticket.id}}" aria-expanded="false" aria-controls="collapse-{{ticket.id}}" id="comments-view-{{ticket.id}}">
                {% endif %}
                    Comments
                    <span class="badge badge-light">
                        {{ticket.ticket_comments}}
                    </span>
                </button>
                
                {% if ticket.file == "" %}
                <button class="btn btn-primary btn-block" disabled>
                    File
                    <span class="badge badge-light">
                        NO
                    </span>
                {% else %}
                <button class="btn btn-primary btn-block" id="file-button-{{ticket.id}}" name="file-button-name" value="{{ticket.id}}">
                    File
                    <span class="badge badge-light">
                        {{ticket.filename}}
                    </span>
                {% endif %}
                </button>
                
                <p>Priority: {{ticket.get_priority_display}}</p>
                <p>Type: {{ticket.get_type_display}}</p>
                
                <p>Status: {{ticket.get_status_display}}</p>
                <div class="collapse mb-2" id="collapse-{{ticket.id}}">
                    <div class="card card-body">
                        <table class="table">
                            <tbody>
                                {% for comment in comments %}
                                    {% if comment.ticket.id == ticket.id %}
                                        <tr>
                                            <th>{{comment.number}}</th>
                                            <td>{{comment.text}}</th>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <button class="btn btn-info ml-1" type="button" data-toggle="modal" data-target="#remove-{{ticket.id}}">Remove</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="remove-{{ticket.id}}" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="header-2">Do you want to remove this ticket from data base?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button class="btn btn-danger" type="submit" value="{{ticket.id}}" name="delete" id="delete-{{ticket.id}}">Yes</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endfor %}

{% if tickets.number %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if tickets.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ tickets.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ tickets.previous_page_number }}">
                    {{tickets.previous_page_number}}
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
        {% endif %}

        <li class="page-item">
            <a class="page-link" href="?page={{ tickets.number }}">
                {{tickets.number}}
            </a>
        </li>

        {% if tickets.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ tickets.next_page_number }}">
                    {{tickets.next_page_number}}
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ tickets.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

Mysite/main/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link rel="icon" href="{% static 'images/logo-removebg-preview.png' %}">
        
        <!--Include Fontawesome icons-->
        <script src="https://kit.fontawesome.com/f749b1610b.js" crossorigin="anonymous"></script>
        <!--Inlcude Bootstrap-->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'main.js' %}"></script>

        {% block title %}
        <title></title>
        {% endblock title %}

    </head>

    <body>
        <header>
            {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg bg-light justify-content-center">
                <div class="collapse navbar-collapse">
                        {% if perms.main.answer_tickets %}
                        <ul class="navbar-nav mr-auto fa-2x">
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="/list_tickets" data-toggle="tooltip" data-placement="bottom" title="Active Tickets">
                                    <div class="icon fa-solid fa-ticket"></div>
                                    <div class="name" data-text="Tickets"><b>Tickets</b></div>
                                </a>
                            </li>
                            <li class="nav-item mr-4"> 
                                <a class="nav-link" href="/knowledge_base" data-toggle="tooltip" data-placement="bottom" title="Knowledge Base">
                                    <div class="icon fa-solid fa-book"></div>
                                    <div class="name" data-text="Knoledge Base"><b>Data</b></div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/dashboard" data-toggle="tooltip" data-placement="bottom" title="Dashboard">
                                    <div class="icon fa-solid fa-table-list"></div>
                                    <div class="name" data-text="Dashboard"><b>Dashboard</b></div>
                                </a>
                            </li>
                        </ul>
                        {% else %}
                        <ul class="navbar-nav mr-auto fa-2x">
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="/tickets" data-toggle="tooltip" data-placement="bottom" title="My Tickets">
                                    <div class="icon fa-solid fa-ticket-simple"></div>
                                    <div class="name mr" data-text="Tickets"><b>Tickets</b></div>
                                </a>
                            </li>
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="/send_ticket" data-toggle="tooltip" data-placement="bottom" title="Send">
                                    <div class="icon fa-solid fa-paper-plane"></div>
                                    <div class="name" data-text="Send"><b>Send</b></div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/dashboard" data-toggle="tooltip" data-placement="bottom" title="Dashboard">
                                    <div class="icon fa-solid fa-table-list"></div>
                                    <div class="name" data-text="Dashboard"><b>Dashboard</b></div>
                                </a>
                            </li>
                        </ul>
                        {% endif %}
                    <ul class="navbar-nav ml-auto fa-2x">
                        <div class="btn-group dropleft">
                            <a href class="nav-link fa-solid fa-bars" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/profile">
                                    <div class="icon fa-solid fa-user"></div>
                                    <div class="name" data-text="Profile"><b>Profile</b></div>
                                </a>
                                <a class="dropdown-item" href="/logout_user"> 
                                    <div class="icon fa-solid fa-right-from-bracket"></div>
                                    <div class="name" data-text="Log Out"><b>Log Out</b></div>
                                </a>
                            </div>
                        </div>
                    </ul>
                </div>
            </nav>
            {% endif %}
        </header>
        
        <section>
            {% block content %}{% endblock content %}
        </section>

        <footer>
            {% block footer-content %}{% endblock footer-content %}
        </footer>
    </body>
</html>